### ISSUE TITLE
HTTPS-проверка не поддерживает TLS 1.2 / 1.3

### ISSUE THREAD

**Issue by Player701** [Zidium/ZidiumServer#1]
На сайте https://player701.ru разрешено использование только TLS версий 1.2 и 1.3 (в перспективе будет только 1.3). [HTTPS-проверка для этого сайта](http://player701.lk.zidium.net/UnitTests/ResultDetails/0479ef01-e3fb-4acc-8cd3-099b3306e95c) выдаёт ошибку: "Запрос был прерван: Не удалось создать защищенный канал SSL/TLS".

**Comment by Zidium** [comment]
На самом деле, поддержку TLS даёт операционная система.
Сейчас облачный Zidium развёрнут на Windows Server 2012 R2. В нём нет поддержки TLS 1.3. Если запустить на сервере IE 11, то он точно так же не может открыть https://player701.ru.
Если развернуть собственный Zidium на более современной ОС, то http-проверки будут работать с TLS 1.3.

**Comment by Zidium** [comment]
На всякий случай, тестовый код для проверки. Выполняется на Win10, не выполняется на Server 2012 R2.

```
using System;
using System.Globalization;
using System.Net;
using System.Threading;

namespace Tls13Test
{
    public class Program
    {
        public static void Main(string[] args)
        {
            Thread.CurrentThread.CurrentCulture = CultureInfo.InvariantCulture;
            Thread.CurrentThread.CurrentUICulture = CultureInfo.InvariantCulture;

            var uri = new Uri("https://player701.ru");
            var request = (HttpWebRequest)WebRequest.Create(uri);
            try
            {
                var response = (HttpWebResponse) request.GetResponse();
                var responseCode = (int)response.StatusCode;
                Console.WriteLine(responseCode);
            }
            catch (Exception exception)
            {
                Console.WriteLine(exception.ToString());
            }

            Console.ReadKey();
        }
    }
}
```

**Comment by Player701** [comment]
На сервере также включен TLS 1.2, но и он тоже почему-то не поддерживается, хотя согласно [материалам с сайта Microsoft](https://docs.microsoft.com/en-us/dotnet/framework/network-programming/tls), TLS 1.2 в Windows Server 2012 R2 поддерживается и включен по умолчанию (см. раздел "Operating system requirements to support TLS 1.2"). Что-то здесь не так.

![image](https://user-images.githubusercontent.com/9046118/63427406-57ecba00-c415-11e9-9c07-1ff0859b7102.png)

**Comment by Zidium** [comment]
На сайте https://player701.ru включен только TLS 1.3, это легко проверить, выключив в браузере поддержку TLS 1.3 - сайт не откроется. Точно так же он не откроется в старом браузере, поддерживающем только TLS 1.2.
Для проверки TLS 1.2 в Zidium можно использовать https://randus.org, он не поддерживает TLS 1.1, только 1.2. Http-проверка к этому сайту успешно выполняется в облаке.

**Comment by Player701** [comment]
Прошу прощения, но я только что выключил в Firefox TLS 1.3 и всё работает с 1.2:

![image](https://user-images.githubusercontent.com/9046118/63462520-6958b500-c45b-11e9-8fe1-56ef3f379108.png)

См. также [тест SSLLabs](https://www.ssllabs.com/ssltest/analyze.html?d=player701.ru), раздел "Configuration" -> "Protocols"

**Comment by Zidium** [comment]
Версия IE 11, которая вообще не знает о TLS 1.3. В ней сайт player701.ru не открывается.
![image](https://user-images.githubusercontent.com/35172658/63490235-419e3700-c4c5-11e9-9d90-c70218521088.png)
![image](https://user-images.githubusercontent.com/35172658/63490273-58dd2480-c4c5-11e9-904a-39edc61dc99d.png)
![image](https://user-images.githubusercontent.com/35172658/63490308-71e5d580-c4c5-11e9-8b9d-4413b7395530.png)

**Comment by Player701** [comment]
Судя по всему, в старых версиях Windows IE 11 не поддерживает используемые на сайте наборы шифров. Все остальные браузеры работают нормально. Подумаю, что можно сделать, но, честно говоря, поддерживать IE 11 не хочется только для того, чтобы работал Zidium.

**Comment by Zidium** [comment]
Ладно Zidium, но ваш сайт не смогут открыть все те, у кого старые браузеры. Тот же randus.org, поддерживающий только TLS 1.2, в старом IE отрывается. Думаю, проблема всё же в настройках шифрования на сайте.

**Comment by Player701** [comment]
Набор шифров TLS_ECDHE_RSA_WITH_AES_128_CBC_SHA, который поддерживает IE11, считается слабым, поэтому по умолчанию он не включен. Как уже говорил ранее, возможно, придётся пересмотреть настройки.

Хотя, если честно, не рекомендую использовать IE вообще.
