### ISSUE TITLE
загрузка конфига в net core в linux

### ISSUE THREAD

**Issue by zmarsel1** [Zidium/ZidiumServer#3]
если запускать приложение не из папки с приложением, то конфиг файл не подтягивается.
попытались загрузить таким образом
`Zidium.Api.Client.Instance.Config = Zidium.Api.XmlConfig.ConfigHelper.Load(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Zidium.config"));
`        
конфиг считывается, но на сервер сообщения не приходят

**Comment by Zidium** [comment]
Можете ли вы предоставить минимальный рабочий пример для воспроизведения проблемы?
Попробуйте вызвать Zidium.Api.Client.Instance.ApiService.GetEcho("Test").Check();
Будет ли ошибка, если да, то какая?

**Comment by zmarsel1** [comment]
вызываем в Startup
```
try
            {
                Zidium.Api.Client.Instance.ApiService.GetEcho("Test").Check();
            }
            catch (Exception ex)
            {
                logger.LogError(ex, ex.Message);
                logger.LogError(ex.StackTrace);
            }
            Zidium.Api.Client.Instance.Config = Zidium.Api.XmlConfig.ConfigHelper.Load(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Zidium.config"));
            try
            {
                Zidium.Api.Client.Instance.ApiService.GetEcho("Test").Check();
            }
            catch (Exception ex)
            {
                logger.LogError(ex, ex.Message);
                logger.LogError(ex.StackTrace);
            }
```
вот таким образом проверили
в первом случае пишет  Не указан AccountName
во втором случае Укажите SecretKey (хотя сам конфиг считал и в Zidium.Api.Client.Instance.Config.Access все данные заполнены )

используем Zidium через NLog. при дебаге в винде всё нормально работает.

**Comment by Zidium** [comment]
Попробуйте такой код:

```
var config = Zidium.Api.XmlConfig.ConfigHelper.Load(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Zidium.config"));

Zidium.Api.Client.Instance = new Zidium.Api.Client(config);

try
{
  Zidium.Api.Client.Instance.ApiService.GetEcho("Test").Check();
}
catch (Exception ex)
{
  logger.LogError(ex, ex.Message);
  logger.LogError(ex.StackTrace);
}

```
То, что сейчас можно напрямую присвоить Zidium.Api.Client.Instance.Config - это недоработка наших классов, такого не должно быть, поправим.

Хотелось бы также понять, почему на линуксе не находится нужный файл Zidium.config.
Наш класс получает его так:

```
var dir = Tools.GetApplicationDir();
var path = Path.Combine(dir, "Zidium.config");
```

Можете посмотреть, что у вас будет в dir? И чему равно typeof(Tools).Assembly.CodeBase во время выполнения?

**Comment by zmarsel1** [comment]
скорее всего проблема присутствует и на windows, если приложение запускать не из папки с приложением(например в качестве windows-сервиса, рабочая папка будет sustem32). на linux мы так же запускаем из корневой папки

**Comment by Zidium** [comment]
Мы это проверим, но вы всё же посмотрите что мы просили в предыдущем сообщении

**Comment by zmarsel1** [comment]
в таком варианте заработало
  ```
 public static void Main(string[] args)
        {
            var config = Zidium.Api.XmlConfig.ConfigHelper.Load(Path.Combine(AppDomain.CurrentDomain.BaseDirectory, "Zidium.config"));
            Zidium.Api.Client.Instance = new Zidium.Api.Client(config);
            CreateHostBuilder(args).Build().Run();
        }

        public static IHostBuilder CreateHostBuilder(string[] args) =>
            Host.CreateDefaultBuilder(args)
                .ConfigureWebHostDefaults(webBuilder =>
                {
                    webBuilder .UseStartup<Startup>();
                })
#if !DEBUG
               .ConfigureAppConfiguration((context, config) =>
               {
                   config.SetBasePath(AppDomain.CurrentDomain.BaseDirectory);
               })
#endif
            .ConfigureLogging((hostingContext, logging) =>
            {
                logging.AddConfiguration(hostingContext.Configuration.GetSection("Logging"));
                logging.ClearProviders();
                logging.SetMinimumLevel(LogLevel.Trace);
                logging.AddDebug();
                logging.AddNLog(hostingContext.HostingEnvironment.IsDevelopment() ? "nlog.config" : $"nlog.{hostingContext.HostingEnvironment.EnvironmentName}.config");
            });
```

**Comment by Zidium** [comment]
А вы какой точно пакет zidium подключаете? Что в элементе < PackageReference >?

**Comment by Zidium** [comment]
Вопрос снят.
В пакете для net core папка приложения определяется как Directory.GetCurrentDirectory();
Дело в том, что средствами net standard 1.6, на который ориентирован наш пакет, невозможно по другому получить путь к приложению.
Поэтому для net core надо или запускать приложение из его собственной папки, или пересоздавать Client, как вы и сделали.
